export const parameterToKey = {
  // "Model hash": "model_hash",
  // Model: "sd_model",
  Sampler: "sampler_name",
  Steps: "steps",
  "CFG scale": "cfg_scale",
  Seed: "seed",
  // "prompt",ƒ
  // "negative_prompt",
  // "sampler_index",
  // "outpath_samples",
  // "outpath_grids",
  // "prompt_for_display",
  // "styles",
  // "subseed_strength",
  // "subseed",
  // "seed_resize_from_h",
  // "seed_resize_from_w",
  // "batch_size",
  // "n_iter",
  // "restore_faces",
  // "tiling",
  // "do_not_save_samples",
  // "do_not_save_grid"
};